version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: javaSpringLR
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 5

  tomcat:
    image: tomcat:9.0-jdk11-temurin
    container_name: tomcat_server
    ports:
      - "8080:8080"
    volumes:
      - ./target/JavaSpringLR.war:/usr/local/tomcat/webapps/JavaSpringLR.war
    depends_on:
      db:
        condition: service_healthy
